version: "3"
services:
  mapogram:
    restart: always
    ports:
      - ${PORT}:80
    build:
      context: ./
      dockerfile: Dockerfile
  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "${POSTGRES_PORT}:5432"