version: "3"
services:
  mapogram:
    restart: always
    ports:
      - ${PORT}:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_DIRECTORY}:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "${POSTGRES_PORT}:5432"